version: "3"
services:
  g:
    image: grafana/grafana
    ports:
    - "3000:3000"
  g2:
    image: grafana/grafana
    ports:
    - "3001:3000"
  p:
    image: prom/prometheus
    volumes:
    - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
    - "9090:9090"